# Generated by Django 5.0.7 on 2024-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('context', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('experience', models.TextField()),
                ('qualities', models.TextField()),
                ('additional_assets', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('reference_code', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('sector', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=255)),
            ],
        ),
    ]
